apiVersion: v1
kind: Service
metadata:
  name: devopscv-backend-service  # Name of the service
spec:
  selector:
    app: devopscv-backend  # This matches the label in the Deployment YAML
  ports:
    - protocol: TCP
      port: 80  # Exposed port
      targetPort: 5000  # Port the backend app listens on inside the container
  type: ClusterIP  # Can be LoadBalancer or NodePort depending on your needs
